name: FreeForAll
version: 1.0
author: IhToN
website: www.minetsii.es
description: FreeForAll Plugin made for MinETSII Network

main: com.deathlyflags.FFA.FFAPlugin

softdepend: [WorldGuard, WorldEdit]

commands:
  ffa: 
    description: /ffa <join|quit|players|setspawn|setquitlocation> 